### ISSUE TITLE
TestShard is flaky

### ISSUE THREAD

**Issue by k1LoW** [k1LoW/runn#103]
TestShard is flaky

ref: https://github.com/k1LoW/runn/pull/95#issuecomment-1214261446

**Comment by k2tzumi** [comment]
refs https://github.com/k1LoW/runn/pull/128#issuecomment-1232290831

**Comment by k1LoW** [comment]
refs: https://github.com/goccy/go-yaml/issues/316

**Comment by k1LoW** [comment]
refs: https://github.com/k1LoW/runn/actions/runs/3068252022/jobs/4955490730#step:6:77

😿

**Comment by k1LoW** [comment]
I think we''ve solved this problem, so Close.
