### ISSUE TITLE
Easily configure shell options

### ISSUE THREAD

**Issue by karrybit** [k1LoW/runn#1093]
Could you support a feature that can easily configure shell options like `set -euo pipefail`?
The reference article is as follows.

- https://taskfile.dev/usage/#set-and-shopt
- https://zenn.dev/shunsuke_suzuki/scraps/172683d8bad652

**Comment by k1LoW** [comment]
Hi @karrybit.

We now support changes to shell execution options (v0.123.0).

https://github.com/k1LoW/runn#execshell

**Comment by karrybit** [comment]
Thanks!
