### ISSUE TITLE
Support to load *.csv file

### ISSUE THREAD

**Issue by karrybit** [k1LoW/runn#1096]
Is it possible to make GraphQL load external files just like JSON or YAML, using something like csv://?
I would greatly appreciate your consideration.

**Comment by k1LoW** [comment]
@karrybit 
Thank you for your request.

There are no plans to support Git root path.

This is because, although the format of CSV files is defined in the RFC, there are many different types that ignore this.
(We think it would be difficult to fully support CSV.)

**Comment by karrybit** [comment]
Thank you for confirming.
