### ISSUE TITLE
Support embedding variables in json files

### ISSUE THREAD

**Issue by k2tzumi** [k1LoW/runn#117]
# Proposal

To allow variables to be embedded in json files for more flexibility as test data.

```json
{
    "code": "{{ vars.code }}",
    "data": {
       "foo": "test",
      "bar": 1
   }
}
```

Use vars syntax to expand variables when reading json.

**Comment by k1LoW** [comment]
Very interesting 👍 

I think the following implementation might be difficult
- Expansion of Integer and Boolean types

**Comment by k2tzumi** [comment]
> Expansion of Integer and Boolean types

I think I was limited to only within a string to expand a variable, so this problem is difficult.

Other tools seemed to have the same problem. 😓 
https://community.postman.com/t/the-path-variable-var-needs-to-be-of-type-integer-but-we-found-var/12714
