### ISSUE TITLE
Compare time.Time

### ISSUE THREAD

**Issue by k2tzumi** [k1LoW/runn#131]
# Proposal

`time.Time` object can now be handled by the following PR
https://github.com/k1LoW/runn/pull/129

I want to define a built-in function for comparison.

* After
* Before
* Equal
May not be necessary as it can be replaced by `Compare`

# Things to consider

* Should it be a generic comparison function that is supposed to handle objects other than the `time.Time` object?
* Is it possible to call a function of struct with `antonmedv/expr`?
For example
`current.rows[0].created_at.After(current.rows[0].updated_at)`
The above syntax does not evaluate correctly, but we think it would be best if we could address this by revising the syntax.

**Comment by k1LoW** [comment]
> Is it possible to call a function of struct with antonmedv/expr?

Maybe, yes.

https://github.com/antonmedv/expr/blob/master/docs/Language-Definition.md#functions-and-methods

**Comment by k1LoW** [comment]
How about having a cast function called `time()` that returns a time.Time type?

**Comment by k1LoW** [comment]
[time()](https://github.com/k1LoW/runn/pull/134) has been added to the built-in functions so that time.Time{} can be compared
