### ISSUE TITLE
Organize call responsibilities for `expr.Eval`

### ISSUE THREAD

**Issue by k2tzumi** [k1LoW/runn#141]
The logic to evaluate an expression against a store is duplicated in several programs.

We are dealing directly with the `antonmedv/expr` library, which we believe is problematic for unified expression expansion.

I think we need to organize the use cases for the process of evaluating expressions, clarify who is in charge of the logic, and do some refactoring.

**Comment by k1LoW** [comment]
Hi @k2tzumi 

We have integrated the functions related to the `expr` package in eval.go

I think this has achieved a certain level of success, but what do you think?

**Comment by k2tzumi** [comment]
@k1LoW 

Yes. I think we have been able to integrate.
Thank you for your response!
