### ISSUE TITLE
vars syntax to read json with relative paths

### ISSUE THREAD

**Issue by k2tzumi** [k1LoW/runn#146]
Currently it is loaded relative to the runn execution path, but I would like to load it relative to the scenario file.
We believe that the above specification is preferable when trying to manage multiple scenario files distributed in multiple directories.

**Comment by k1LoW** [comment]
I agree with the proposal 👍 

There is one thing we need to be concerned about.
There may be a case in the future where the Runbook is not a file.

- When YAML is passed as a string instead of a file in Go code
- When YAML is passed from STDIN
