### ISSUE TITLE
Supports file upload

### ISSUE THREAD

**Issue by k2tzumi** [k1LoW/runn#223]
# Items to consider

* How do you want the file to be specified?
* How to determine content type?
* Is multipart/form-data support only required?

**Comment by k1LoW** [comment]
We can upload from `<form>` via Chrome 👍 

https://github.com/k1LoW/runn/blob/1fbd4cb6e54c1d84add3d22b1543d3bc0d681645/cdp_test.go#L177-L259

**Comment by atsushi-ishibashi** [comment]
@k1LoW Do you have any plans to upload files as multi-part via http?

**Comment by k1LoW** [comment]
Not a high priority at the moment, but "Yes."

I think the goal of this Issue is to achieve file uploading with HTTP Runner.

( I have not yet gotten around to this issue at all. )

**Comment by atsushi-ishibashi** [comment]
I'm glad to hear that👍
Can I try this issue until you are ready?

**Comment by k1LoW** [comment]
@atsushi-ishibashi GREAT!!!!!!!!

Your try will be successful before I start implementing it.

**Comment by k2tzumi** [comment]
@atsushi-ishibashi @k1LoW 

Thank you so much!
I really appreciate it.
