### ISSUE TITLE
Bind stdin from users' interactive

### ISSUE THREAD

**Issue by atsushi-ishibashi** [k1LoW/runn#296]
For example, email verification code step or MFA step.
book design image. Wait for users' stdin input at `stdin` runner step.
```
desc: Exec test
steps:
  -
    stdin:
      comment: 'Get MFA code: '
      (optional)timeout:
  -
    req:
      /hoge/{{ steps[0].stdin.value }}
```

If `exec` can solve what I want, please let me know!

When we have the concensus, I'll contribute👍

**Comment by k1LoW** [comment]
Thank you for your request!

I have 3 questions

1. Is the feature you want to input values from outside the runbook?
2. For example, can't it be entered by an environment variable?
3. Is there a reason you would like to enter it in the middle of the steps run?
    - For example, would entering all the values at the beginning of a runbook run satisfy your requirement?

**Comment by atsushi-ishibashi** [comment]
>Is the feature you want to input values from outside the runbook?

yes.

>For example, can't it be entered by an environment variable?

yes.

>Is there a reason you would like to enter it in the middle of the steps run?

yes.
Considering email verification or MFA senario so those aren't determined when I run book.

Email verification
1. Open signup page via cdp
2. Input email and password
3. Send email with verification code to real email address
4. Input verification code into runbook 

MFA
1. Signin request via http
2. Got one time password via login email or got OTP via MFA application(like google authenticator)
3. Input the code into runbook

**Comment by k1LoW** [comment]
Thank you.

The MFA can be automated by emulating OTP (but only for go test code using [Func](https://pkg.go.dev/github.com/k1LoW/runn#Func)).
Email Verification seems to be difficult indeed.

I'm wondering how to implement this.

**Comment by k1LoW** [comment]
How about implementing it with a built-in function?

**Comment by k1LoW** [comment]
How about an implementation like [this](https://github.com/k1LoW/runn/pull/297)?

**Comment by atsushi-ishibashi** [comment]
At first, I consider whether it can be realized with existing features like built-in func👌

**Comment by atsushi-ishibashi** [comment]
Thank you for your quick implementation. I'll check it later

**Comment by atsushi-ishibashi** [comment]
Looks good!
What I want seems to be realized with #297 . thanks

**Comment by atsushi-ishibashi** [comment]
works well. thanks!
```
desc: prompt
runners:
  req: https://example.com
vars:
  id: hoge
steps:
  prompt0:
    bind:
      otp: input("Enter otp> ", "")
  prompt1:
    bind:
      password: secret("Enter pass> ")
  prompt2:
    bind:
      choice: select("Choose > ", ["one", "two"], "")
  fuga:
    desc: fuga
    req:
      /?otp={{ otp }}&password={{ password }}&choice={{ choice }}:
        get:
          body:
            application/json: null

// output
Run 'bind' on 'prompt'.steps.prompt0
Enter otp> : hoge

Run 'bind' on 'prompt'.steps.prompt1
Enter pass> : 

Run 'bind' on 'prompt'.steps.prompt2
Choose >  (one/two): two

Run 'req' on 'prompt'.steps.fuga
-----START HTTP REQUEST-----
GET /?choice=two&otp=hoge&password=pass HTTP/1.1
Host: example.com
Content-Type: application/json
```
