### ISSUE TITLE
Got error: `multipart: NextPart: EOF`

### ISSUE THREAD

**Issue by atsushi-ishibashi** [k1LoW/runn#326]
I got multipart error at server side.
```
code=400, message=multipart: NextPart: EOF, internal=multipart: NextPart: EOF
```

**Comment by atsushi-ishibashi** [comment]
I made code sets to reproduce error
https://github.com/atsushi-ishibashi/runn-repro-326

**Comment by atsushi-ishibashi** [comment]
I detected the below reset body caused it and when you set header again, you will get success.
https://github.com/k1LoW/runn/blob/e43ef04aa7b5c09c9a1542a3ad339730fdab8d55/http.go#L228

**Comment by atsushi-ishibashi** [comment]
Considering this PR and #310 , I think no one has used it yet so can I make breaking change for multipart body format to simplify implementation?
（このPRの不具合を鑑みるとまだ僕以外は誰も使ってないと思うので #310 の修正で互換性維持するために難しい実装になるくらいなら互換性壊す修正にしても良いですか？）

**Comment by atsushi-ishibashi** [comment]
I cannot imagine how to support map and slice in a simple way.
```
values, ok := r.body.(map[string]interface{})
&&
values, ok := r.body.([]interface{})
```

**Comment by k1LoW** [comment]
> I think no one has used it yet so can I make breaking change for multipart body format to simplify implementation?

OK 👍

**Comment by k1LoW** [comment]
> I cannot imagine how to support map and slice in a simple way.

I often use type-switch to solve that problem.

https://go.dev/tour/methods/16
