### ISSUE TITLE
Is it possible to use SSL certificate with http protocol?

### ISSUE THREAD

**Issue by HirokiMurakoshi** [k1LoW/runn#393]
Thanks for the great tool.

Is it possible to use SSL certificate with http protocol?
In GRPC, cert and key can be specified in runners, but is it possible to specify the same in HTTP?

I checked the ReadMe and couldn't find it, so I asked a question. I am sorry if I have overlooked it.

**Comment by k1LoW** [comment]
We don't have that setting now.
But we think it would be nice to have.

**Comment by HirokiMurakoshi** [comment]
@k1LoW 
Thank you for confirmation.

**Comment by HirokiMurakoshi** [comment]
@k1LoW 
Thank you for adding this! That helps a lot!

**Comment by k1LoW** [comment]
@HirokiMurakoshi Thank you for your report! THIS IS BUG. I'll fix asap..

**Comment by HirokiMurakoshi** [comment]
@k1LoW 
Thank you for confirmation. Sorry for the inconvenience, but thank you in advance.

**Comment by k1LoW** [comment]
@HirokiMurakoshi Released as v0.58.2.

**Comment by HirokiMurakoshi** [comment]
@k1LoW 
Thank you for your prompt response.
I was able to confirm that I can communicate normally using the SSL certificate.
thank you very much.
