### ISSUE TITLE
Can't put DB value in template

### ISSUE THREAD

**Issue by HirokiMurakoshi** [k1LoW/runn#429]
I would like to use the template function added here to dynamically enter the DB value.
https://github.com/k1LoW/runn/issues/117

When I specified as follows, an error occurred at the "[" part.
```
{
  "id": {{.steps.getIdFromDB.rows[0].id}}
}
```
How can I put the DB value dynamically? Sorry to trouble you, but please confirm.

**Comment by k1LoW** [comment]
Templates for variables use text/template package. You can use `{{ index .rows 0 }}` instead of `rows[0]`

**Comment by HirokiMurakoshi** [comment]
@k1LoW 
Sorry for the delay. Thank you for answering.
Even if I replaced the above as it is, an error occurred, so when I tried various things, the following code worked as expected.

```
{
  "checkInId": "{{with index .steps.getCheckinId.steps.dbRequest.rows 0 }}{{ .checkin_id }}{{ end }}"
}
```

It can't be helped because it's the way text/template is written, but it's hard to write. . .

**Comment by HirokiMurakoshi** [comment]
This has been resolved, so I will close it. Thank you for your answer.
