### ISSUE TITLE
Is it possible to specify a json file relative to the execution path?

### ISSUE THREAD

**Issue by HirokiMurakoshi** [k1LoW/runn#449]
When reading the json file with the following correspondence, it has been changed to read with the relative path from the scenario file.
https://github.com/k1LoW/runn/issues/146

The above response itself is very convenient and helpful. thank you.

However, as shown below, when the commonly used setting values ​​are put in another folder, if the path from the executable file
```
json://../../Common/SettingParam.json
```
Is there a way to describe the relative path from the execution path of runn?

```
runn
  - Common
    - SettingParam.json
  - TestCase
    - TestCaseA
      - TestCase1.yaml
      - TestCase2.yaml
    - TestCaseB
      - TestCase1.yaml
```

**Comment by k1LoW** [comment]
The following seems to work correctly

https://github.com/k1LoW/runn/blob/f4146da3662de3ead1bedea6b42e936373743f4a/testdata/book/vars_external.yml#L2-L6

If you can give me the smallest runbook and json where the problem occurs, I might be able to figure something out.

**Comment by HirokiMurakoshi** [comment]
I'm sorry, the relative path from the executed yaml is working properly.
For example, when the above is written from TestCase1.yaml, it can be obtained without problems.

The question is whether it is possible to set the path from the runn folder as shown below instead of the path from the executed file.
```
## TestCase1.yaml

vars:
  pathA: json://../../Common/SettingParam.json
  pathB: json://Common/SettingParam.json  ## I want to write like this
```

**Comment by k1LoW** [comment]
> The question is whether it is possible to set the path from the runn folder as shown below instead of the path from the executed file.

Unfortunately, it is not supported. Because runn wants to be able to resolve paths in any working directory.

**Comment by HirokiMurakoshi** [comment]
Thank you for answering.
I understand that it is not possible to specify the path as above.
Write the path relative to the executable file.
