### ISSUE TITLE
What are some possible ways to have a unique id issued for each scenario?

### ISSUE THREAD

**Issue by k2tzumi** [k1LoW/runn#515]
We would like to number the requests with an ID that can identify the scenario in order to trace from which scenario the request was made during regression testing.

What are the possible methods?
I would like to consider extending runn if necessary.

Examples of the use of unique IDs may include the following.

* Set in the x-header of the request
* Used in code value when creating data

**Comment by k1LoW** [comment]
If you are using runn as a package, it is possible to define your own functions.

If you need a fixed unique ID for each scenario each time, you may need to extend runn.

**Comment by k2tzumi** [comment]
Some ideas for numbering unique IDs are summarized below

Refer to the desc in the runbook so that it can be utilized as an ID
Prefix the ID with a combination of the runbook file name and step name, and use a timestamp as the suffix.
