### ISSUE TITLE
Allow HTTPRunner to take over cookies

### ISSUE THREAD

**Issue by k2tzumi** [k1LoW/runn#548]
Currently, you have to explicitly create a scenario to take over cookies, but it would be nice to have a mode to easily take over.

**Comment by k1LoW** [comment]
I agree with your opinion 👍

**Comment by k2tzumi** [comment]
After much discussion on the whiteboard, we came to an agreement on what we would do 👍 

![FzcmuOBaQAIRiM-](https://github.com/k1LoW/runn/assets/1182787/715fca99-f78d-4b80-bc39-d2330c2f967e)

**Comment by k1LoW** [comment]
@k2tzumi GREAT WORK!!! Thank you!!
