### ISSUE TITLE
Too many connections error occurs when multiple scenarios run

### ISSUE THREAD

**Issue by cxconj** [k1LoW/runn#606]
runn v0.81.1

Because a db connection is created each scenario and it is not closed after running the scenario, `Too many connections` error occurs when exceeding max connection limit.
Example: https://gist.github.com/cxconj/126d0848e62c273b06be037576f6cfd4

If the connection is closed after each scenario, the error will not occur, but it will affect not only the `runn` command but also the functions when runn is used as go pkg.
https://github.com/cxconj/runn/commit/327fa9fc393ddadf70ec255e61f82405a05d6c83

**Comment by k1LoW** [comment]
@cxconj Thank you for your report!!

> but it will affect not only the runn command but also the functions when runn is used as go pkg.

You are right.
We'll try to find a solution.

**Comment by k1LoW** [comment]
@cxconj 
Thanks to you, including providing the code for reference, I was able to solve the problem. Thank you very much.

**Comment by cxconj** [comment]
Thanks for the quick fix! I have confirmed that it works correctly.
