### ISSUE TITLE
Support SSH Proxy

### ISSUE THREAD

**Issue by k2tzumi** [k1LoW/runn#614]
I would like to make HttpRunner communication via SSH port forwarding.
Need to consider whether to separate or unify settings with other Runners.

**Comment by k1LoW** [comment]
Already possible in combination with SSH Runner 🚀 

https://github.com/k1LoW/runn/blob/131b656b7efda2012b09901e4a55fab5f357ff7f/testdata/book/sshd_local_forward_with_openapi3.yml#L1-L21

**Comment by k2tzumi** [comment]
We were able to achieve this!
Thank you!
