### ISSUE TITLE
Specify the header name for the trace header

### ISSUE THREAD

**Issue by k2tzumi** [k1LoW/runn#704]
By default, the trace header is fixed to the header `X-Runn-Trace`.

Allow header names to be specified as follows

```yaml
runners:
  myapi:
    endpoint: https://api.github.com
    trace:
      enable: true
      headername: "request-id"
```

**Comment by k1LoW** [comment]
What are some cases in which you would like to change the header name?

**Comment by k2tzumi** [comment]
see.
https://rarejob-tech-dept.hatenablog.com/entry/2020/03/19/190000

The application under test had the ability to log unique IDs between microservices and we wanted to use runn's unique Id as is.

**Comment by k1LoW** [comment]
It looks good about adding the ability to change the header name 👍 

On the other hand, if it is necessary to change the format of the trace ID, it would be better to consider it as a separate feature.

**Comment by k2tzumi** [comment]
@k1LoW 

We are considering making existing fixed header names constant.
Is it intended that the notation is different between gRPC and HTTP? If it is not a problem, we would like to unify them, but we would like your opinion.

**Comment by k1LoW** [comment]
> Is it intended that the notation is different between gRPC and HTTP?

HTTP headers are expressed in CamelCase, but gRPC headers only allow lowercase letters.

However, since it is lowercased inside, it should be able to be constant value without any problem.

https://github.com/grpc/grpc-go/blob/dbbcf59957fec0bd58063224cbf105b3b3698d4e/metadata/metadata.go#L116
