### ISSUE TITLE
[Feature Request] Make concurrency field accepts multiple values

### ISSUE THREAD

**Issue by h6ah4i** [k1LoW/runn#770]
Hi. I think it would be great if runn accepts multiple values in the [`concurrency:`](https://github.com/k1LoW/runn?tab=readme-ov-file#concurrency) field.

### Current behavior
Only one string can be specified to the `concurrency:` field. Runbooks with the same key are assured of a single run at the same time.

### Expected behavior
One string or multiple strings (list) can be specified to the `concurrency:` field. Runbooks with **any of the same keys** are assured of a single run at the same time.

**Comment by k1LoW** [comment]
Looks good to me!
