### ISSUE TITLE
🐛 bug: Error messages are not displayed correctly

### ISSUE THREAD

**Issue by okazaki-kk** [k1LoW/runn#792]
Hello! thanks to the great tools.

I build on the latest main branch with `make build` command and run the incorrect runbook, but the error message does not display.

```
➜  runn git:(main) ✗ make build
go build -ldflags="-X github.com/k1LoW/runn.commit=$(git describe --tags --always) -X github.com/k1LoW/runn.date=$(date --utc '+%Y-%m-%d_%H:%M:%S')" -o runn cmd/runn/main.go
➜  runn git:(main) ✗ ./runn --version                 
runn version 0.98.4
➜  runn git:(main) ✗ ./runn run testdata/duplicate.yml ⇦ does not display error message 
➜  runn git:(main) ✗ 
```

Correct behavior
```
$ runn --version                 
runn version 0.98.3

$ runn run testdata/duplicate.yml
Error: failed to load runbook testdata/duplicate.yml: duplicate step keys: a.   ⇦ display error message correctly
$ 
```

I think the cause is this commit. https://github.com/k1LoW/runn/pull/789/commits/f67d81822fe6fa325674febbc7b76e62224ee597
When revert this commit and build again, the error message displayed correctly

**Comment by k1LoW** [comment]
@okazaki-kk Thank you for your report!
