### ISSUE TITLE
Including string literal `{{ ... }}` in HTTP request body

### ISSUE THREAD

**Issue by bearmini** [k1LoW/runn#828]
Hi, my API accepts handlebars template notations so I want to test the API with request body like the following:

```
{
  "messageTemplate":"Hello {{name}}!"
}
```

So I specified `req` runner like the following:

```
req:
  post:
    headers:
      ...
    body:
      application/json:
        messageTemplate: "Hello {{name}}!"
```

But the `{{name}}` part is interpreted as variable substitution by `runn` and we don't have any variable named `name`, so actual request body sent to my API was: `{"messageTemplate":"Hello  !"}`

To avoid get `{{name}}` interpreted as variable, I tried some escaping method like the followings, but no luck:

- Attempt 1:
```
messageTemplate: "Hello \{\{name\}\}!"
```
=>  resulted in actual request body:
```
{"messageTemplate":"Hello \\{\\{name\\}\\}!"}
```
which is not what I want.

- Attempt 2: 
```
messageTemplate: "{{ 'Hello {{name}}' }}"`
```
=> resulted in `literal not terminated` error: :shrug: 
```
         |  'Hello {{name
         | ..............^
```

- Attempt 3:
```
messageTemplate: >-
  Hello {{name}}!
```
=> resulted in actual request body: 
```
{"messageTemplate":" "}
```

How can I specify `{{ ... }}` literal in my request body?

**Comment by k1LoW** [comment]
Hmmm... it's possible that [expand](https://github.com/k1LoW/expand) package does not support this.
It would be better to be able to handle it, so I'll check.

**Comment by k1LoW** [comment]
Hi @bearmini.

Delimiters can be escaped in v0.100.0.

```
messageTemplate: "Hello \{\{name\}\}!"
```

Please try it.

**Comment by k1LoW** [comment]
Please re-open if you still have problems.

Thank you!!
