### ISSUE TITLE
OpenAPI validation fails for range of response codes (4XX, 5XX, ...)

### ISSUE THREAD

**Issue by h6ah4i** [k1LoW/runn#881]
In OpenAPI, we can describe response status codes like this.

```yaml
      responses:
        '200':
          description: OK
        '4XX':
          description: Bad request.
        '5XX':
          description: Unexpected error.
```

The `4XX`/`5XX` part is called **range of response codes** syntax in the OpenAPI spec and it is completely valid. However, runn gives error like the following;

> Failure/Error: http request failed on "*** openapi3 validation error: Error: POST operation request response code '404' does not exist, Reason: The reponse code '404' of the POST request submitted has not been defined, it's an unknown type, Line: ***, Column: ***

ref.) https://swagger.io/docs/specification/describing-responses/

(I have not confirmed yet, but it seems pb33f/libopenapi does not support the syntax.)

**Comment by k1LoW** [comment]
ref: https://github.com/pb33f/libopenapi-validator/pull/65
