### ISSUE TITLE
[Feature request] Time instance creation built-in functions

### ISSUE THREAD

**Issue by h6ah4i** [k1LoW/runn#926]
I want to test APIs that use UNIX timestamps. Is there a chance to add [time#Unix()](https://pkg.go.dev/time#Unix), [time#UnixMilli()](https://pkg.go.dev/time#UnixMilli), and [time#UnixMicro()](https://pkg.go.dev/time#UnixMicro) as built-in functions?

FYI: We can parse datetime strings using the [date()](https://expr-lang.org/docs/language-definition#date) function that expr provides, but it does not support parsing UNIX timestamps.

**Comment by k1LoW** [comment]
Looks good, I thought it would be good to implement a similar configuration to [faker](https://github.com/k1LoW/runn/blob/35a5ea75436ab5179e3d21ca59acff3a203ce240/option.go#L1230).

On the other hand, the currently existing `time()` can also manipulate Unix timestamps, so a careful transition based on use cases is necessary.

**Comment by h6ah4i** [comment]
> On the other hand, the currently existing time() can also manipulate Unix timestamps, so a careful transition based on use cases is necessary.

Wow! I have't noticed that because the `time()` built-in is not listed on the [README section](https://github.com/k1low/runn?tab=readme-ov-file#additional-built-in-functions). Can you add this to help people can easily find the function?

**Comment by k1LoW** [comment]
Added! 👍
