### ISSUE TITLE
[Feature request] Allow negative filtering by labels

### ISSUE THREAD

**Issue by h6ah4i** [k1LoW/runn#934]
Hi. I think it would be convenient if runn had more flexibility in filtering runbooks.

```bash
## examples
runn run path/to/**/*.yml --label !foo
runn run path/to/**/*.yml --label '!foo and !bar'
```

However, I am aware that introducing negative operator into the current label option can be troublesome. If possible, it might be better to introduce a new option that allows users to freely filter using the expr syntax.

```bash
## examples
runn run path/to/**/*.yml --filter '!labels.foo and !labels.bar'

runn run path/to/**/*.yml --filter '!labels.foo' --filter '!labels.bar'
#  converted to  => (!labels.foo) and ('!labels.bar)

runn run path/to/**/*.yml --filter '!labels["foo"]' --filter '!labels["bar"]'
#  converted to  => (!labels["foo"]) and ('!labels["bar"])
```

**Comment by k1LoW** [comment]
@h6ah4i Thank you for your request!

Could your requirements be met with features such as #935?
