### ISSUE TITLE
How to mock GCP, cloudstorageAdapter.SignUrl?

### ISSUE THREAD

**Issue by dungtqbap** [k1LoW/runn#976]
I write API test base on the guild [runn Grpc server](https://github.com/k1LoW/runn?tab=readme-ov-file#run-n-runbooks-using-grpcserver)

My runn is working fine on other requests, but I'm having trouble mocking the return value when making the GCP call, cloudStorageAdapter.SignUrl.

Can you share what you know about mocking when sending requests to GCP and receiving responses?

Many thanks

**Comment by k1LoW** [comment]
@dungtqbap Thanks for using runn.

We are still not quite sure what you want to achieve, but we will answer your question first.
Unfortunately, runn does not have a mock feature. It may be necessary to incorporate another mechanism.

**Comment by dungtqbap** [comment]
@k1LoW 
I am using a combination of runn and wiremock to simulate the results returned when calling google's cloudStorage.
Do you have an example for that, or if you have any suggestions please let me know
